# Generated by Django 6.0.4 on 2026-06-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('unpublished', 'Снят с публикации')], default='draft', max_length=20, verbose_name='Статус публикации'),
        ),
    ]
