# Generated by Django 6.0.4 on 2026-06-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_status_product_published_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['published_status'], 'permissions': [('can_unpublish_product', 'может отменять публикацию продукта'), ('can_delete_product', 'может удалять продукт')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
